### ISSUE TITLE
A directory to be synced. 

### ISSUE THREAD

**Issue by dwhan89** [ACTCollaboration/sync-nersc-scinet#4]
Hey, can you add following two directories to the sync list?

SCINET ---> NERSC

-  /home/r/rbond/saiola/map_release/D56_20160624  -------> /project/projectdirs/act/data/synced_maps/D56_20160624

-   /home/r/rbond/saiola/map_release/D5_6_20160628 ------> /project/projectdirs/act/data/synced_maps/D5_6_20160628

**Comment by msyriac** [comment]
Added. Scinet's datamover seems to be down, so it isn't syncing currently.

**Comment by msyriac** [comment]
Syncing now

**Comment by dwhan89** [comment]
Awesome. Thanks!

**Comment by dwhan89** [comment]
/global/project/projectdirs/act/data/synced_maps/D56_20160624 is not fully synced; there are missing files.
I thought your rsync script runs daily. Isn't that the case?

**Comment by msyriac** [comment]
There is a timeout issue that I need to understand and address. Since I haven't addressed it, I have not set up nightly syncs yet.

I've restarted the sync now.
